language: java
before_script:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git config --global user.email "${GIT_NAME}"
- git config --global user.name "${GIT_EMAIL}"
- git clone https://github.com/oteichmann/artifact-repo /home/travis/build/oteichmann/artifact-repo
script:
- mvn -P arquillian-embedded -Dinternal.snapshotRepository.path=file:///home/travis/build/oteichmann/artifact-repo clean deploy
after_success:
- cd /home/travis/build/oteichmann/artifact-repo
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git remote rm origin
- git remote add origin https://oteichmann:${GH_TOKEN}@github.com/oteichmann/artifact-repo.git
- touch test
- git commit -am "test"
- git push origin master
env:
  global:
    secure: Ca5aEtnnq3AyEe4eicYcDA40ACJdWZzDm+ZcpuywQNtIMfAK+tbLN7v48hUsspTRk95ehy9FmT4OlV9wIuxo6ReAIq49BESB8g8gCu7R5NwRB2Hq9SCJvTlUSYHPrgwxIdD2sVbFvlM+VfRbwm4bQW1ofb6MWP5rEmPBMvo0OOE=
